# 开发环境配置
server:
  port: 8080

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/api_foundation?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Myh202021

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.backend: debug
    root: info