# 生产环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_foundation_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.backend: info
    root: warn
  file:
    name: /var/log/api-foundation/application.log